version: '3.8'

services:
  web:
    build: .
    container_name: csms-web
    restart: always
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://csms:csmspassword@db/csms
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: csms-celery
    restart: always
    command: celery -A src.celery_worker.celery worker --loglevel=info
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://csms:csmspassword@db/csms
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.21-alpine
    container_name: csms-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/csms.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/app/static
    depends_on:
      - web

  db:
    image: mysql:8.0
    container_name: csms-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=csms
      - MYSQL_USER=csms
      - MYSQL_PASSWORD=csmspassword
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:6.2-alpine
    container_name: csms-redis
    restart: always
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: 